import bc125py

VERSION = bc125py.MODULE_VERSION

CLI_PROGRAM_NAME = bc125py.MODULE_NAME
CLI_PROGRAM_DESCRIPTION = bc125py.MODULE_DESCRIPTION

CLI_COMMAND_VERBOSE_HELP = "verbose mode"
CLI_COMMAND_SUBCOMMAND_HELP = "command"
CLI_COMMAND_SUBCOMMAND_TEST_HELP = "test scanner connection"
CLI_COMMAND_SUBCOMMAND_READ_HELP = "read data from scanner, output to file"
CLI_COMMAND_SUBCOMMAND_READ_FILE_HELP = "output file"
CLI_COMMAND_SUBCOMMAND_WRITE_HELP = "write data from file to scanner"
CLI_COMMAND_SUBCOMMAND_WRITE_FILE_HELP = "input file"
CLI_COMMAND_SUBCOMMAND_SHELL_HELP = "launch interactive scanner shell"